import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";
import InstallPWAButton from "@/components/InstallPWAButton";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata = {
//     title: "Sv Leiben ",
//     description: "Generated by create next app",
//     manifest: "/manifest.json",
// };

export const metadata = {
  title: 'Sv Leiben',
  description: 'Generated by create next app',

  // 1️⃣ Web App Manifest
  // If you have a static `public/manifest.json`,
  // Next.js will auto-generate:
  //   <link rel="manifest" href="/manifest.json" />
  // Otherwise, you can drop a `app/manifest.json` file
  // per the file-convention :contentReference[oaicite:0]{index=0}
  manifest: '/manifest.json',

  // 2️⃣ Icons for browsers & home-screen
  icons: {
    icon: '/icons/icon-192.png',
    shortcut: '/icons/icon-512.png',
    apple: '/icons/icon-192.png',
  },

  // 3️⃣ iOS “Add to Home Screen” meta
  appleWebApp: {
    capable: true,
    title: 'FootVid',
    statusBarStyle: 'black-translucent',
  },  // :contentReference[oaicite:1]{index=1}
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  // 4️⃣ theme-color for Android status bar
  themeColor: '#0a0a0a',
};

export default function RootLayout({ children }) {
    return (
        <html lang="de" className="dark">
         
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ServiceWorkerRegister />
                {children}
                <InstallPWAButton />
            </body>
        </html>
    );
}
