# .github/workflows/scrape.yml
name: Hourly Table Scrape

on:
  # enable manual runs from the UI
  workflow_dispatch:

  # keep your hourly schedule
  schedule:
    - cron: '0 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npx playwright install   
      - run: npm run scrape
