# .github/workflows/scrape.yml
name: Hourly Table Scrape

on:
  # Manual trigger in the UI
  workflow_dispatch:
  # Cron schedule: at minute 0 of every hour (UTC)
  schedule:
    - cron: '0 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      # these must be set in your repo Settings → Secrets → Actions
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install system Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper & save to Supabase
        run: npm run scrape
